# For use with pre-commit.
# See usage instructions at https://pre-commit.com
repos:

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, "2", --preserve-quotes]

- repo: https://github.com/adrienverge/yamllint
  rev: v1.25.0
  hooks:
  - id: yamllint

- repo: https://github.com/ansible/ansible-lint
  rev: v4.3.5
  hooks:
  - id: ansible-lint
