# For use with pre-commit.
# See usage instructions at https://pre-commit.com
repos:

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, "2", --preserve-quotes]

- repo: https://github.com/adrienverge/yamllint
  rev: v1.37.1
  hooks:
  - id: yamllint

- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8

- repo: https://github.com/ansible/ansible-lint
  rev: v25.9.2
  hooks:
  - id: ansible-lint
    files: \.(yaml|yml)$
