dependency:
  name: galaxy
  options:
    role-file: ansible-role-requirements.yml
    requirements-file: collections.yml
driver:
  name: docker
platforms:
- name: instance
  image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
  command: ${MOLECULE_DOCKER_COMMAND:-""}
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - /var/lib/containerd
  cgroupns_mode: host
  privileged: true
  pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
  env:
    ANSIBLE_LIBRARY: ${MOLECULE_PROJECT_DIRECTORY}/library
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
