dependency:
  name: galaxy
  options:
    role-file: ansible-role-requirements.yml
driver:
  name: docker
platforms:
- name: instance
  image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
  command: ${MOLECULE_DOCKER_COMMAND:-""}
  privileged: true
  pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
