dependency:
  name: galaxy
  options:
    role-file: ansible-role-requirements.yml
driver:
  name: docker
lint: |
  set -e
  ansible-lint
  black . --check
  flake8
  yamllint .
platforms:
- name: instance
  image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
  command: ${MOLECULE_DOCKER_COMMAND:-""}
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: true
  pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
