dependency:
  name: galaxy
  options:
    role-file: ansible-role-requirements.yml
driver:
  name: docker
platforms:
- name: instance
  image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
  command: ${MOLECULE_DOCKER_COMMAND:-""}
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - /var/lib/containerd
  cgroupns_mode: host
  privileged: true
  pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
