- name: Verify
  hosts: all
  become: true

  tasks:
  - name: Run role without running any tasks
    include_role:
      name: dokku_bot.ansible_dokku
      tasks_from: init.yml

  # Testing dokku_global_cert
  - name: Check that dokku_global_cert module can parse output
    dokku_global_cert:
      state: absent

  # Testing dokku_hostname
  - name: Get dokku_hostname    # noqa 301
    command: dokku domains:report --global
    register: dokku_domains

  - name: Check that dokku_hostname is set correctly
    assert:
      that:
      - "'test.domain' in dokku_domains.stdout"
      msg: |
        hostname 'test.domain' not found in output of 'dokku domains':
        {{ dokku_domains.stdout }}

  # check apt sources configuration
  # Note: cannot use apt module for this https://stackoverflow.com/questions/51410696
  - name: Run apt update  # noqa 303 301
    command: apt-get update
    register: apt_update

  - name: Check that apt update output does not contain warnigns
    assert:
      that:
      - "'W:' not in apt_update.stderr"
      msg: |
        Found warnings in output of `apt update`:
        {{ apt_update.stderr }}

  # Testing dokku_clone
  - name: clone example-app
    dokku_clone:
      app: example-app
      repository: https://github.com/heroku/node-js-getting-started
      version: b10a4d7a20a6bbe49655769c526a2b424e0e5d0b

  - name: Get list of apps  # noqa 301
    command: dokku apps:list
    register: dokku_apps

  - name: Check that example-app is in list of apps
    assert:
      that:
      - "'example-app' in dokku_apps.stdout"
      msg: |
        'example-app' not found in output of 'dokku apps:list':
        {{ dokku_apps.stdout }}

  - name: clone example app again
    dokku_clone:
      app: example-app
      repository: https://github.com/heroku/node-js-getting-started
      version: b10a4d7a20a6bbe49655769c526a2b424e0e5d0b
      build: false
    register: example_app

  - name: Check that re-cloning example app did not change anything
    assert:
      that:
      - not example_app.changed
      msg: |
        Re-cloning example app resulted in changed status
